name = "day_01"
description = ""
version = "0.1.0-dev"

authors = ["OppenheimerK"]
maintainers = ["OppenheimerK <kristof.schoenfelder@web.de>"]
maintainers-logins = ["OppenheimerK"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["day_01"]
